#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINCOMPOSE, UNICODE_MODE_MACOS
#define UNICODE_CYCLE_PERSIST false
#define LEADER_TIMEOUT 300 